application: g1plus-engine
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(html|ico|png|jpg|gif))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif))

# secure cronjobs (no access for normal user)
#- url: /tasks/crawl
#  script: rss.py
#  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"